version: "3"
services:
  db:
    image: postgres
    container_name: postgreSQL
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_DB=stardium_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    restart: always