version: "3"
services:
  domain_db:
    image: postgres
    container_name: StardiumPostgreSQL
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_DB=stardium_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    restart: always

  chat_db:
      image: redis
      container_name: SrardiumRedis
      ports:
        - "16379:6379"
      environment:
